version: '3.7'

services:

  client:
    build:
      context: ./client
    command: node server.js
    volumes:
      - ./client/public:/app/public
    tty: true
    stdin_open: true
    environment:
      - CLIENT_PORT=3579

  admin-tool:
    build:
      context: ./admin-tool
    command: yarn start
    volumes:
      - ./admin-tool/src:/app/src
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_API_PORT=8080
      - REACT_APP_API_URL=api

  api:
    build:
      context: ./api
    command: yarn run dev
    volumes:
      - ./api/src:/app/src
      - ./api/public:/app/public
    environment:
      - PORT=3001
      - DB_PORT=27017
      - DB_URL=db
      - DB_NAME=hopkins
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - hopkins_db:/data/db
    ports:
    - '13579:27017'
    command: [--auth]

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin-tool
      - api


volumes:
  hopkins_db:
